## Syllabus {.unnumbered}

**Course description**: Data Sci for Lang & Mind is an entry-level course designed to teach basic principles of statistics and data science to students with little or no background in statistics or computer science. Students will learn to identify patterns in data using visualizations and descriptive statistics; make predictions from data using machine learning and optimization; and quantify the certainty of their predictions using statistical models. This course aims to help students build a foundation of critical thinking and computational skills that will allow them to work with data in all fields related to the study of the mind (e.g. linguistics, psychology, philosophy, cognitive science, neuroscience).

**Prerequisites**: There are *no prerequisites beyond high school algebra*. No prior programming or statistics experience is necessary, though you will still enjoy this course if you already have a little. Students who have taken several computer science or statistics classes should look for a more advanced course.

**Lectures**: Tuesdays and Thursdays from 12 - 1:29pm in TBD.

**Instructor**: [Dr. Katie Schuler (she/her)](https://kathrynschuler.com)

**TAs**: Brittany Zykoski and Wesley Lincoln 

**Labs**: Hands-on practice and exam prep guided by TAs.

* 402: Thu at 1:45p in TBD
* 403: Thu at 3:30p in TBD
* 404: Fri at 3:30p in TBD
* 405: Fri at 12:00p in TBD

**Office Hours**: You are welcome to attend any office hours that fit your schedule. The linguistics department is located on the 3rd floor of 3401-C Walnut street, between Franklin's Table and Modern Eye. 

- Katie Schuler: TBD in 314C
- Brittany Zykoski: TBD in TBD
- Wesley Lincoln: TBD in TBD

**Grading**:

- 40% Homework (equally weighted, lowest dropped)
- 60% exams (equally weighted, final is optional to replace lowest exam)

**Collaboration**: Collaboration on problem sets is highly encouraged! If you collaborate, you need to write your own code/solutions, name your collaborators, and cite any outside sources you consulted (you don't need to cite the course material).

**Accomodations**: We will support any accommodations arranged through Disability Services via the [Weingarten Center](https://weingartencenter.universitylife.upenn.edu/disability-services/). Please make arrangements as soon as possible (1-2 weeks in advance).

**Extra credit**: There is no extra credit in the course. However, students can submit any missed problem set or exam by the end of the semester for half credit (50%).  To ensure fair treatment, all students will receive a 1% "bonus" to their final course grade: 92.54% will become 93.54%.

**Regrade requests** Regrade requests should be submitted through Gradescope within one week of receiving your graded assignment. Please explain why you believe there was a grading mistake, given the posted solutions and rubric


<!-- ## Lectures

Tuesdays and Thursdays from 12 - 1:29pm in TBD.

- **Week 1 (Aug 27) -- R Basics**: [Notes]() / [Slides]() / [Demo]() 
- Week 2 (Sep 3) -- Importing and tidying data: [Notes]() / [Slides]() / [Demo]() 
- Week 3 (Sep 10) -- Data visualization: [Notes]() / [Slides]() / [Demo]() 
- Week 4 (Sep 17)-- Sampling distribution: [Notes]() / [Slides]() / [Demo]() 
- Week 5 (Sep 24) -- Hypothesis testing: [Notes]() / [Slides]() / [Demo]() 
- Week 6 (Oct 1) -- Exam 1  
- Week 7 (Oct 8) -- Model specification 
- Week 8 (Oct 15) -- Model fitting
- Week 9 (Oct 22) -- Model accuracy 
- Week 10 (Oct 29) -- Model reliability 
- Week 11 (Nov 5) -- Classification 
- Week 12 (Nov 12) -- Exam 2
- Week 13 (Nov 19) -- Inference 
- Week 14 (Nov 26) -- Thanksgiving break (no class)
- Week 15 (Dec 3) -- Multilevel models
- Week 16 (Dec 10) -- Last day of class 
- Week 17 (TBD) -- Final exam (optional) -->






